version: '2'
services:
  kafka:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      ADVERTISED_HOST: "kafka"
      ADVERTISED_PORT: 9092
      TOPICS:

  order:
    build: ../order
    depends_on:
      - "kafka"
      - "mongoorder"
  mongoorder:
   image: mongo
   ports:
    - "27017"
   expose:
    - "27917"
 