version: '3.2'

services:
  order:
    build: ./order
    image: order
    container_name: order
    depends_on:
    - "kafka"
    stdin_open: true
  coursier:
    build: ./coursier
    image: coursier
    depends_on:
    - "mongo_coursier"
    - "kafka"
    container_name: coursier
    stdin_open: true
  restaurant:
    build: ./restaurant
    image: restaurant
    container_name: restaurant
    depends_on:
    - "mongo_restaurant"
    - "kafka"
    stdin_open: true
  coursierws:
    build: ./coursier-ws
    image: coursier-ws
    depends_on:
    - "kafka"
    container_name: coursierws
    expose:
    - "8099"
    ports:
    - "8099:3000"
    stdin_open: true
  restaurantws:
    build: ./restaurant-ws
    image: restaurant-ws
    depends_on:
    - "kafka"
    container_name: restaurantws
    expose:
    - "8098"
    ports:
    - "8098:3000"
    stdin_open: true
  customerws:
    build: ./customer-ws
    image: customer-ws
    depends_on:
    - "kafka"
    container_name: customerws
    expose:
    - "8097"
    ports:
    - "8097:3000"
    stdin_open: true
  eta_calculator:
    build: ./eta_calculator
    image: eta_calculator
    container_name: eta_calculator
    depends_on:
      - "kafka"
    stdin_open: true
  mongo_coursier:
   image: mongo
  mongo_delivery_man:
    image: mongo
  mongo_restaurant:
    image: mongo
  mongo_payment:
    image: mongo
  kafka:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      ADVERTISED_PORT: 9092
      ADVERTISED_HOST: "kafka"
      AUTO_CREATE_TOPICS: "true"
  delivery_man_account:
    build: ./delivery_man_account
    image: delivery_man_account
    depends_on:
    - "mongo_delivery_man"
    - "kafka"
    container_name: delivery_man_account
    stdin_open: true
  payment:
    build: ./payment
    image: payment
    depends_on:
    - "mongo_payment"
    - "kafka"
    container_name: payment
    stdin_open: true