version: '3.2'

services:
  order:
    build: ./order
    image: order
    container_name: order
    expose:
      - "8000"
    ports:
      - "8000:3000"
    stdin_open: true
  coursier:
    build: ./coursier
    image: coursier
    depends_on:
      - "mongo"
    container_name: coursier
    expose:
      - "8090"
    ports:
      - "8090:3000"
    stdin_open: true
  restaurant:
    build: ./restaurant
    image: restaurant
    container_name: restaurant
    expose:
      - "8080"
    ports:
      - "8080:3000"
    stdin_open: true
  eta_calculator:
    build: ./eta_calculator
    image: eta_calculator
    container_name: eta_calculator
    expose:
    - "9090"
    ports:
    - "9090:9090"
    stdin_open: true
  mongo:
   image: mongo
   environment:
     - MONGO_INITDB_ROOT_USERNAME=soauser
     - MONGO_INITDB_ROOT_PASSWORD=soa
   expose:
        - "27017"
   ports:
        - "27017:27017"
  mongocoursier:
   image: mongo
   expose:
        - "27016"
   ports:
        - "27016:27017"
  kafka:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      ADVERTISED_PORT: 9092
