version: '3.2'

services:
  order:
    build: ./order
    image: order
    container_name: order
    expose:
      - "8000"
    ports:
      - "8000:3000"
    stdin_open: true
  coursier:
    build: ./coursier
    image: coursier
    depends_on:
    - "mongo"
    container_name: coursier
    expose:
    - "8090"
    ports:
    - "8090:3000"
    stdin_open: true
  coursierws:
    build: ./coursier-ws
    image: coursier-ws
    depends_on:
    - "kafka"
    container_name: coursierws
    expose:
    - "8099"
    ports:
    - "8099:3000"
    stdin_open: true
  restaurant:
    build: ./restaurant
    image: restaurant
    container_name: restaurant
    expose:
      - "8080"
    ports:
      - "8080:3000"
    stdin_open: true
  restaurantws:
    build: ./restaurant-ws
    image: restaurant-ws
    depends_on:
    - "kafka"
    container_name: restaurantws
    expose:
    - "8098"
    ports:
    - "8098:3000"
    stdin_open: true
  eta_calculator:
    build: ./eta_calculator
    image: eta_calculator
    container_name: eta_calculator
    expose:
    - "9090"
    ports:
    - "9090:9090"
    stdin_open: true
  mongo:
   image: mongo
   environment:
     - MONGO_INITDB_ROOT_USERNAME=soauser
     - MONGO_INITDB_ROOT_PASSWORD=soa
   expose:
        - "27017"
   ports:
        - "27017:27017"
  mongocoursier:
   image: mongo
   expose:
        - "27016"
   ports:
        - "27016:27017"
  mongo_delivery_man:
    image: mongo
    expose:
    - "27018"
    ports:
    - "27018:27017"
  mongo_payment:
    image: mongo
    expose:
    - "27019"
    ports:
    - "27019:27017"
  kafka:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      ADVERTISED_PORT: 9092
      ADVERTISED_HOST: "kafka"
      AUTO_CREATE_TOPICS: "true"
  delivery_man_account:
    build: ./delivery_man_account
    image: delivery_man_account
    depends_on:
    - "mongo_delivery_man"
    - "kafka"
    container_name: delivery_man_account
    stdin_open: true
  payment:
    build: ./payment
    image: payment
    depends_on:
    - "mongo_payment"
    - "kafka"
    container_name: payment
    stdin_open: true