FROM uberoo-commons:latest
RUN mkdir /eta_calculator
COPY ./dist /eta_calculator/dist
COPY ./package.json /eta_calculator/
WORKDIR /eta_calculator
RUN npm install --production
EXPOSE 3000
ENTRYPOINT [ "npm","start"]